version: "3.9"

networks:
  ros_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:

  ros2_ignition:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: ros2-humble-ignition

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

      - ROS_IP=172.20.0.10
      - ROS_MASTER_URI=http://172.20.0.10:11311

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    networks:
      ros_network:
        ipv4_address: 172.20.0.10

    ports:
      - "11311:11311"

    privileged: true

    stdin_open: true
    tty: true
    
    
